[package]
name = "iced-test-aya-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { version = "0.12", optional = true }
bstr = { version = "1.10.0", default-features = false }

[lib]
path = "src/lib.rs"
